### ISSUE TITLE
The preprocess module can not generate files as expected

### ISSUE THREAD

**Issue by dwang55** [zekarias-tilahun/deepred#1]
The description of preprocessing module in markdown file says we should hold the raw interation.txt in raw_dir, while the code in preprocess.py read the raw interaction.txt from processed_dir actually.  It will be helpful to clean the code carefully to make it easier for others to reproduce the paper. Anyway, thanks for opening source the code.

**Comment by zekarias-tilahun** [comment]
Hi,

Thank you for  catching this error and checking out our work. We have started cleaning the code and already pushed the first version. Now, it should run smoothly. Please let us know if you run into any problem while using the current version.

**Comment by dwang55** [comment]
> Hi,
> 
> Thank you for catching this error and checking out our work. We have started cleaning the code and already pushed the first version. Now, it should run smoothly. Please let us know if you run into any problem while using the current version.

The current version of the code can run smoothly, and the code is easier to read.  Thanks for your prompt response!
